### PR TITLE
Allow command blocks to create islands.

### PR DESCRIPTION
**Pull request by ghost**
Assuming this is the actual issue with command blocks not getting "enough permission" to run this?

### CODE REVIEW

**Comment by meza** [comment]
👍

**Comment by TheCricket** [comment]
squash your commits please

**Comment by Kolatra** [comment]
I can squash it.

**Comment by kolatra** [comment]
My only issue with this change is that it allows anybody to create islands on a server, I'd like to keep creation to OP only.

EDIT: I've gotten this to work, I've just omitted the canCommandSenderUseCommand override.

**Pull request closed without merging**
