### PR TITLE
Add hashCode() to the pos

### PR DESCRIPTION
**Pull request by sameer**
eY B0ss Pls Boss!

### CODE REVIEW

**Comment by sameer** [comment]
Includes transition to NBT and compaction of y coordinate storage.

**Comment by TheCricket** [comment]
I don't approve of the format

**Comment by sameer** [comment]
Please suggest an alternate format

**Comment by TheCricket** [comment]
We're already working on it. I have been at PAX since wednesday so not much time to work on it

**Comment by sameer** [comment]
Oh nice, sounds good.

**Pull request closed without merging**
